name: Publish to Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Build & Publish
    if: ${{ !endsWith(github.event.head_commit.message, '[skip-ci]') }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Maven Central Repository
      run: mvn deploy
      env:
        MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
